name: Metrics - Activity
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          base: ""
          token: ${{ secrets.PROFILE_KEY }}
          optimize: svg
          experimental_features: --optimize-svg
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics activity"
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
